mautic/documentation

leads/README.md, points/README.md
Noticed these typos while trying to figure out Mautic.
=> Fixed a couple typos in documentation.

leads/README.md, leads/lead_monitoring.md, leads/managing_leads.md
I fixed a few typos and added some bits to the lead section.  Wasn't sure how you wanted images handling so haven't added any.
I made a few structural changes which I felt helped the text to flow better as well.
=> Fixing typos and updated lead section

forms/manage_forms.md
Added a section on creating/updated leads.
=> Update to form documentation

themes/customize_themes.md
Changed Customise to Customize
=> Update and rename customise_themes.md to customize_themes.md

leads/lead_monitoring.md
1. Double quote instead of single quote
2. Unnecessary space removed
3. alt attribute added to comply with HTML standard IMG tag
=> Tracking pixel code snippet made valid

leads/lead_monitoring.md
Ref: https://www.mautic.org/community/index.php/891-using-mautic-in-mobile-app/0#p3633
=> Added mobile support

SUMMARY.md, emails/troubleshooting.md, leads/lead_monitoring.md, pages/troubleshooting.md
Mauticans are asking "Why the tracking isn't working?" questions over and over. It'd be great to have a link were to redirect them. Or possibly, where they could look up the answer themselves.
Suggestions are welcome.
=> Tracking troubleshooting

forms/manage_forms.md
The most of the text is stolen from Alan's text in the forum:
https://www.mautic.org/community/index.php/307-using-mautic-for-event-registration/0
=> Form pre-populate feature described

leads/lead_monitoring.md
Missing host was pointed out in this conversation:
https://github.com/mautic/mautic/issues/882#issuecomment-158400625
=> tracking page url php exapmle fixed

emails/bounce_management.md
I didn't know about this feature until Alan described it in an unrelated PR test. I thought it should be documented for the community.
=> Described how to create a bounced email lead list

README.md
=> Added the tutorial about how to contribute to the docs 

README.md
While testing I saw a few typos, so I decided to edit them.
=> Josephbojang patch 1

emails/troubleshooting.md
Documented invalid URL issue (https://github.com/mautic/mautic/issues/1439)
=> Valid URL note added to the email troubleshooting

README.md
Replace "probalby"  to "probably" on Image section in README.md
=> Fix misspelled word in README.md

campaigns/campaign_builder.md
Explain the different behavior of the app about the waiting time of attached actions for `Decisions` and `Conditions`.
=> Update campaign_builder.md about waiting time of attached actions for Decisions and Conditions.

forms/manage_forms.md
We noticed that when you paste twice the same injection code on a page, it generates troubles when the form is submitted without value in the mandatory fields.
* https://github.com/mautic/mautic/issues/1162
=> Warning for double form code pasting

SUMMARY.md, emails/mailer_is_owner.md
Documentation for https://github.com/mautic/mautic/pull/1319. Merge after that PR is merged.
=> Mailer owner

en/leads/lead_overview.md
In this case there are already contacts and segments instead of leads and lists.
=> Lead overview documented

jp/SUMMARY.md
just fix the small typo in jp/SUMMARY.md.
=> fix typo in jp/SUMMARY.md

en/setup/cron_jobs.md
Added cron job information for the new `mautic:maintenance:cleanup` command. See https://github.com/mautic/mautic/pull/2024
=> Added cron job information on new data cleanup job

en/contacts/managing_contacts.md
Docs for https://github.com/mautic/mautic/pull/2133
=> Contact duplicates documented

jp/setup/cron_jobs.md, jp/setup/getting_started.md
Changed the description of tracking code, and so on.
=> Update Japanese documents

en/setup/cron_jobs.md
To address the need for social monitoring Cron example, ref https://github.com/mautic/documentation/issues/89
=> Add Cron Job Example for Social Monitoring

en/contacts/contact_monitoring.md
https://github.com/mautic/mautic/pull/2550
=> Added a note on mtc_id cookie

en/SUMMARY.md, en/companies/README.md, en/companies/companies.md
=> company documentation

en/setup/cron_jobs.md
https://github.com/mautic/mautic/pull/2259
=> Added documentation for broadcast sending

en/emails/README.md
This has the documentation for the click counts of a link in an email
=> Documentation for the click count of a link in the email

en/forms/manage_forms.md
Docs for https://github.com/mautic/mautic/pull/2427
=> Form style documented

plugins/outlook.md
Documentation for mautic/mautic#2175
=> Added documentation for the Outlook plugin

SUMMARY.md, en/plugins/social_login.md
=> social login documentation

en/emails/bounce_management.md
Removed Sendgrid and added SparkPort.
=> Fixed a typo

en/contacts/manage_fields.md, en/contacts/managing_contacts.md
Docs for https://github.com/mautic/mautic/pull/2616
=> Updated docs about Boolean values import

en/plugins/salesforce.md
I'm guessing this was meant to be SSL, not SSH. The latter doesn't make sense in this context.
=> SSH vs SSL

en/plugins/salesforce.md
Some quick proof reading changes
=> A couple of spelling type-o's

en/contacts/contact_monitoring.md
In the PR mautic/mautic#2950 the JS tracking is changed. Now the tracking based exclusively on cookies. This PR adds a paragraph to the docs.
=> Tracking based on cookies

en/companies/README.md
=> Company merge docs

en/plugins/salesforce.md
The code is using relative urls for the links, but not for the images. This means that the images do not displayed on github or on a local system.
=> Relative urls for images for salesforce docs

en/plugins/salesforce.md
Adding documentation on the specifics of using the "Update Contact Owner" feature for the Salesforce integration
=> Documentation for Salesforce Update Contact Owner

en/forms/manage_forms.md
https://github.com/mautic/mautic/pull/2936
=> Remove Contact from Do Not Contact

en/plugins/salesforce.md
=> Salesforce Updates

en/companies/README.md
=> Company scoring documentation

en/SUMMARY.md, en/contacts/import.md
Added missing docs for contact import inspired by https://github.com/mautic/mautic/issues/1543
=> Contact import documented

en/campaigns/campaign_events.md
=> Minor changes in Campaign Events

en/setup/cron_jobs.md
Updated broken link on line 74 and fixed link syntax on line 90.
=> Link fixes

en/focus/README.md
https://mautic.org/docs/en/focus/index.html
=> Fixes typos on focus page

en/plugins/dynamics_crm.md
Fixed image urls in Dynamics Documentation
=> Fixed image urls in Dynamics Documentation

README.md
=> README minor grammar

en/tips/README.md
https://github.com/mautic/mautic/pull/3549
=> Add information about max entity lock time EN

en/video/README.md
https://github.com/mautic/mautic/pull/4480
=> Tracked videos

fr/contacts/manage_segments.md
correct mistakes and forgotten translation on segment page.
=> correct french manage segment page

en/campaigns/campaign_events.md
https://github.com/mautic/mautic/pull/4357
=> Campaign action: Send a webhook

en/campaigns/campaign_events.md, en/focus/README.md
Added docs for https://github.com/mautic/mautic/pull/4666
=> Campaign Action: Show Focus Item

en/plugins/outlook.md, fr/plugins/outlook.md
According to the topic on the forum https://www.mautic.org/topic/outlook-add-in/ i've added the mention of 2013 compatibility.
=> add the mention of outlook 2013 compatibility

en/queue/README.md
See https://github.com/mautic/mautic/pull/3873 for more info.
=> User documentation for Queue Bundle

VARIABLES.MD
=> List of all known Mautic Tokens

en/sms/README.md
Changed description:
- Text messages are now handled via Twilio Plugin
- Removed the generic description (from general settings)
=> Changed description for text message configuration

en/contacts/README.md
The screenshot path was absolute.
I've fixed it to relative
=> Fix screenshot path

en/emails/manage_emails.md
https://github.com/mautic/mautic/pull/6237
=> Support for date format modifier to tokens

en/assets/manage_assets.md
https://github.com/mautic/mautic/pull/5667
=> Added option to noindex assets by search bots

en/pages/manage_pages.md
https://github.com/mautic/mautic/pull/5730
=> Disable search indexing with noindex on landing page

en/campaigns/campaign_events.md
https://github.com/mautic/mautic/pull/5720
=> Update contact's primary company

en/plugins/sugarcrm.md
https://github.com/mautic/mautic/pull/5896
=> SugarCRM support for DNC sync

en/contacts/contact_monitoring.md
Re: https://github.com/mautic/mautic/pull/6422
=> added documentation for track_private_ip_ranges option

en/stages/stages.md
=> corrected typo - contact's in stages.md

en/campaigns/campaign_events.md
Docs for https://github.com/mautic/mautic/pull/6539
=> IP address token for campaign webhook action documented

en/plugins/pipedrive.md
https://github.com/mautic/mautic/pull/5401
=> Pipedrive full sync

en/contacts/manage_segments.md
https://github.com/mautic/mautic/pull/6993
=> Added relative date support to anniversary/birthday

en/forms/README.md
Hello folks. Does anyone know is there a documentation for this feature? cc @alanhartless https://github.com/mautic/mautic/blob/2.15.1/media/js/mautic-form-src.js#L41-L70
Here is related discussion in discord:
=> Added example of opening a form in modal when call-to-action button is clicked

VARIABLES.MD
As seen in https://www.mautic.org/docs/en/forms/manage_forms.html
=> Document usage of url encoding values

en/contacts/contact_monitoring.md
=> fix language in URL tracking section of contact monitoring page

en/emails/bounce_management.md
I spent a couple of hours scratching my head why I couldn't get Amazon to confirm my topic subscription.  So let's try to avoid others having the same struggle.
=> Give more hints on setting up Amazon SNS topic subscriptions

en/contacts/managing_contacts.md
#109 add link on reference to search docs page
=> Small update to point to new page

en/contacts/README.md, en/contacts/managing_contacts.md
Made a start at improving the contacts docs - mostly grammatical changes.
=> Improve contacts docs

en/companies/README.md
=> companies: reformat Markdown

CONTRIBUTING.md, README.md, en/README.md
=> new `index.html` for https://www.mautic.org/docs/en

CONTRIBUTING.md, README.md, VARIABLES.md, en/README.md, en/contacts/customize_preference_center.md, en/contacts/import.md, en/forms/manage_forms.md
=> :memo: fix documentation links and markdown

en/assets/manage_assets.md, en/authentication/saml.md, en/campaigns/campaign_builder.md, en/campaigns/campaign_events.md, en/categories/categories.md, en/channels/README.md, en/components/README.md, en/contacts/contact_monitoring.md, en/contacts/contact_overview.md, en/contacts/contact_preference_center.md, en/contacts/manage_segments.md, en/contacts/managing_contacts.md, en/contacts/message_queue.md, en/dashboard/README.md, en/dwc/README.md, en/emails/README.md, en/emails/bounce_management.md, en/emails/contact_replies.md, en/emails/manage_emails.md, en/focus/README.md, en/pages/manage_pages.md, en/points/README.md, en/reports/README.md, en/sms/README.md, en/social-monitoring/README.md, en/themes/code_mode.md, en/themes/manage_themes.md, en/translations/README.md, en/video/README.md
- en/plugins in a separate PR.
- en/notifications has an open PR
- en/forms updated during contribution day
=> en/*: use relative images

en/emails/manage_emails.md
According to https://github.com/mautic/mautic/pull/7811
=> add info about token usage in from address field
