setup/README.md

As of 1.1.3 this is no longer required as the command line scripts default to the production environment.

Remove env config from cron jobs

---

emails/bounce_management.md

`mautic:list:update` does not exist:
https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Command/UpdateLeadListsCommand.php#L23-L33
Replaced with existing command updating lead lists.

app/console mautic:list:update command does not exist

---

setup/getting_started.md

Both links at https://www.mautic.org/docs/setup/getting_started.html now goes to 404 pages. This PR should fix that.

Getting Started link fix

---

en/plugins/README.md

Referenced in this bug report https://github.com/mautic/mautic/issues/2354

Added reference to clearing the cache when installing a new plugin

---

README.md

When this is published to https://mautic.org/docs/en/index.html this should link to github repo.

Add link to github repo

---

en/plugins/citrix.md

there was am istake inside the documentation
this is not 
php app/console citrix:sync
but :
php app/console mautic:citrix:sync

added mautic: prefix in the cronjob to use

---

en/plugins/citrix.md

This PR updates the Citrix documentation to include the new "Join Webinar" button token documentation.

Citrix GoToWebinar Button token documentation

---

en/contacts/contact_monitoring.md

mautic handdles more UTM tags than listed in the documentation.
There's no info that user MUST create a form with "record utm tags" action if he wants to keep the utm tags.

UTM tags doc updated

---

README.md

I have fixed what I think is a broken link, which was pointing at the docs with /index.html.  This results in a pretty poor UI with huge flags and tiny text links.  
I think it would be better to drop them on the main docs page which has the option to easily change the language as required.
I've added the links to the multilingual PDF downloads, as the single link was broken.

Fix some broken links and add multilingual PDF download links

---

en/contacts/contact_monitoring.md

Adding documentation for mautic/mautic#3398 which allows wildcards in the CORS domain.

Documentation for allowing a wild card character in CORS domains

---

en/setup/cron_jobs.md

Add description of cron setting for Report scheduler (https://github.com/mautic/mautic/pull/5205)

Add report scheduler cron to documentation

---

en/setup/cron_jobs.md

I've noticed that a number of queries in #support on Slack revolve around how to configure Cron.
This PR provides a link to a well written document by the Apache Foundation on how to configure crontabs

Add a link to the apache foundation cron document

---

en/emails/troubleshooting.md
en/pages/troubleshooting.md

The troubleshooting checklists for emails and pages were not being rendered correctly:
- https://www.mautic.org/docs/en/emails/troubleshooting.html
- https://www.mautic.org/docs/en/pages/troubleshooting.html
I think this is because Markdown lists require a blank line before they start, but I can't be sure due to #311 and #312.

Add missing blank line before Markdown lists

---

en/SUMMARY.md
en/tips/update-failed.md

Adding documentation page to help users with a failed update (with agreement from @escopecz to bring the content in from his fantastic article)

Add update failed documentation

---

en/emails/README.md
en/emails/manage_emails.md

Place the tracking pixel image freely within the message body as alternative to the default placement at the end of the <body>.

Placement of tracking pixel token in email

---

en/SUMMARY.md
en/tips/command-line.md

I am often finding I have to search for these so have pulled all the commands I could see as being relevant to a Mautic user into one table.
I didn't include all the doctrine commands etc as I think that isn't so relevant to the end-user, and I included at the start how to find them all if needed.
Fingers crossed the formatting looks half-decent!

Add documentation of CLI commands

---

en/setup/cron_jobs.md

I didn't notice any --segment-id parameter for mautic:broadcast:send command

Remove --segment-id from broadcast:send

---

en/setup/cron_jobs.md
fr/setup/cron_jobs.md
jp/setup/cron_jobs.md

Changed confusing campaign update command name usage in cron jobs docs. We should use one command name in example and campaign description. 
Linked topics:
[https://github.com/mautic/mautic/issues/5436](url)
[https://forum.mautic.org/t/cron-jobs-whats-the-difference/11177/2](url)

Use one campaign update command name in cron_jobs

---

CONTRIBUTING.md
README.md
en/README.md

was: https://github.com/mautic/documentation/CONTRIBUTING.md
correct: https://github.com/mautic/documentation/blob/master/CONTRIBUTING.md

Use correct URL for CONTRIBUTING.md

---

VARIABLES.md

This PR removes from documentation variables that do not exist in preferences center landing page.

Remove undefined preference center variables
